/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AllPeriyodik.java
 *
 * Created on 07.Tem.2009, 16:14:02
 */

package org.zoda.model;

import org.zoda.gui.*;
import org.zoda.model.*;
import java.util.List;
import org.zoda.dao.impl.PeriodicDao;

/**
 *
 * @author Lord
 */
public class AllPeriyodik extends javax.swing.JFrame {
    private static final long serialVersionUID = 1L;

    /** Creates new form AllPeriyodik */
    public AllPeriyodik() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Listele");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Tüm periyodikleri listele");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel1)
                .addGap(71, 71, 71)
                .addComponent(jButton1)
                .addContainerGap(96, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1))
                .addContainerGap(166, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        PeriodicDao pd = new PeriodicDao();

        List<Periodic> list = pd.list(Periodic.class);

        for(Periodic per:list){
            System.out.println(per.getPerson().getName());
            System.out.println(per.getPerson().getSurname());

       List<PersonEmployee> li = per.getPerson().getEmployees();
       for (PersonEmployee pm: li) {
            System.out.println(pm.getTelsic());
            System.out.println(pm.getCompany().getCompanyName());
        }


            System.out.println(per.getDatePeriodic());
        }





    }//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AllPeriyodik().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

}
